#!/usr/bin/env bash
# Route hermes.growgig.tech -> Hermes app via the host nginx reverse proxy.
#
#  - Only Cloudflare edge IPs may connect (hitting the VPS IP directly with a
#    Host header gets 403), and the real client IP is restored from
#    CF-Connecting-IP for logging and rate limiting.
#  - Per-IP rate limit on /chat, request body cap, timeouts sized for agent runs.
#  - If a Cloudflare Origin Certificate exists at $CERT/$KEY, nginx also serves
#    HTTPS on :443 so you can set Cloudflare SSL mode to "Full (strict)"
#    (with plain :80 only, use "Flexible" — traffic CF->VPS is then unencrypted).
#
# Prefer zero open ports? Use the Cloudflare Tunnel profile in docker-compose.yml
# instead of this script.
#
# Run on the VPS:  cd /docker/hermes-app && git pull && bash scripts/setup-nginx.sh
set -euo pipefail

HOST=hermes.growgig.tech
APPDIR=/docker/hermes-app
CERT=/etc/ssl/cloudflare/hermes.pem
KEY=/etc/ssl/cloudflare/hermes.key
CONF=/etc/nginx/conf.d/hermes.conf

cd "$APPDIR"

# ── 1. Make sure /chat is protected ──────────────────────────────────────────
if ! grep -qE '^HERMES_API_KEY=.+' .env 2>/dev/null; then
    NEWKEY=$(openssl rand -hex 32)
    if grep -q '^HERMES_API_KEY=' .env 2>/dev/null; then
        sed -i "s/^HERMES_API_KEY=.*/HERMES_API_KEY=$NEWKEY/" .env
    else
        echo "HERMES_API_KEY=$NEWKEY" >> .env
    fi
    echo ">> Generated HERMES_API_KEY (saved in .env). Clients must send:"
    echo "   Authorization: Bearer $NEWKEY"
fi

# ── 2. Rebuild + restart the app (without --build, code changes never ship) ──
echo ">> Building and starting container on 127.0.0.1:8700..."
docker compose up -d --build

# ── 3. Cloudflare IP ranges ──────────────────────────────────────────────────
echo ">> Fetching Cloudflare IP ranges..."
CF_IPS=$( { curl -fsS https://www.cloudflare.com/ips-v4; echo; curl -fsS https://www.cloudflare.com/ips-v6; } | grep -E '^[0-9a-fA-F:.]+/[0-9]+$' )
if [ "$(echo "$CF_IPS" | wc -l)" -lt 10 ]; then
    echo "!! Could not fetch Cloudflare IP list — aborting without touching nginx." >&2
    exit 1
fi

# ── 4. nginx site ────────────────────────────────────────────────────────────
echo ">> Writing $CONF for $HOST..."
{
    echo "# Generated by scripts/setup-nginx.sh — re-run the script to refresh Cloudflare IPs."
    echo "limit_req_zone \$binary_remote_addr zone=hermes_chat:10m rate=30r/m;"
    echo
    echo "# 1 if the TCP peer (before real_ip rewriting) is a Cloudflare edge node."
    echo "geo \$realip_remote_addr \$hermes_from_cf {"
    echo "    default 0;"
    echo "$CF_IPS" | sed 's/^/    /; s/$/ 1;/'
    echo "}"
    echo
    echo "server {"
    echo "    listen 80;"
    if [ -f "$CERT" ] && [ -f "$KEY" ]; then
        echo "    listen 443 ssl;"
        echo "    ssl_certificate $CERT;"
        echo "    ssl_certificate_key $KEY;"
    fi
    echo "    server_name $HOST;"
    echo
    echo "$CF_IPS" | sed 's/^/    set_real_ip_from /; s/$/;/'
    cat <<'NGINX'
    real_ip_header CF-Connecting-IP;

    if ($hermes_from_cf = 0) {
        return 403;
    }

    client_max_body_size 256k;
    limit_req_status 429;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

    location = /chat/stream {
        limit_req zone=hermes_chat burst=10 nodelay;
        proxy_pass http://127.0.0.1:8700;
        proxy_buffering off;
        proxy_read_timeout 300s;
    }

    location /chat {
        limit_req zone=hermes_chat burst=10 nodelay;
        proxy_pass http://127.0.0.1:8700;
        proxy_read_timeout 120s;
    }

    location / {
        proxy_pass http://127.0.0.1:8700;
    }
}
NGINX
} > "$CONF.new"

mv "$CONF" "$CONF.bak" 2>/dev/null || true
mv "$CONF.new" "$CONF"
if ! nginx -t; then
    echo "!! nginx config test failed — restoring previous config." >&2
    mv "$CONF.bak" "$CONF" 2>/dev/null || rm -f "$CONF"
    exit 1
fi
systemctl reload nginx

echo "=== DONE ==="
echo ">> nginx routes $HOST -> 127.0.0.1:8700 (Cloudflare IPs only)"
if [ -f "$CERT" ]; then
    echo ">> HTTPS origin enabled: set Cloudflare SSL/TLS mode to Full (strict)."
else
    echo ">> No origin cert at $CERT — CF->VPS hop is plain HTTP. For end-to-end TLS,"
    echo "   create a Cloudflare Origin Certificate, save it to $CERT / $KEY, re-run."
fi
curl -s -o /dev/null -w ">> local app health: HTTP %{http_code}\n" http://127.0.0.1:8700/health || true
